[package]
org = "ballerinax"
name = "EncounterAPI"
version = "1.0.3"
export = ["EncounterAPI"]
distribution = "2201.5.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Encounter","r4","international"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
