[package]
org = "ballerinax"
name = "smartConfig"
version = "1.0.1"
export = ["smartConfig.config","smartConfig.constants","smartConfig.handlers","smartConfig.models"]
distribution = "2201.5.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","SMART"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
